apiVersion: v1
kind: Secret
metadata:
  name: nguyent4-secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQVNJQVZGSFpZVFhZN0E2NFVGRlQKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gL1psOTA0RWJiekFzNzBpcStsSGxhZkNzL0psaTJoOVN2M2diTVNIWQphd3Nfc2Vzc2lvbl90b2tlbiA9IEZ3b0daWEl2WVhkekVHZ2FET0tDTkNJZE1PbHczT2RQOVNMVkFRbEZ6akxML1VwTzJnZ0lZd0U3UU1qSGlMS2U5Mk1MN0tINVR5NEVvMHNrTjAxNzhzTlY2cGlTS0MwQU1yYlMrQS8vUS8zQ1ZROUxNbldlSnlRcUJLWFlPTXVCQXJIUkU0d2U3Rit2bDltdEpsdWtQRENZb1dtc1A1b1RBRldhamp2eHJhWjdrb0crZlpmeFJzeVNRTlZvOEk3VnhMZjdOM3JOWkcxTGtja00vZGtMdGJMTWZpRkFDbVRQb2VLZmliRG5oM1ZLbC85S2pCWUF3S1pkWlh1Z1NERUszblVvWis3ODFWQk1HSjM3RUF2S2tndXBrUDQwMzBPUVNveFV6ZURodDk4SUY3MXEyK2N2MUtYbEUwK3FkZ2I4dFNqaTYrR21Cakl0ZEY1b1AzeitYejdvYVR6V28wbmRNTzVXd2JxV0pjcWlHWEZ4RjdpalpkeE9vZXgrQVBBSlNScU5ITnlz